---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Gathering Facts
      become: false
      setup:
        gather_subset:
          - '!all'
          - network
          - hardware
    - name: Update Package Cache (Apt)
      apt:
        update_cache: true
        cache_valid_time: 360
  roles:
    - role: hwwilliams.mosh
